spring.application.name=TpFoyee
spring.datasource.url=jdbc:mysql://localhost:3306/tpfoyee?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration :
server.port=8082
server.servlet.context-path=/TpFoyee
